name: Wokwi testing

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test temperature
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          path: /
          timeout: 10000
          fail_text: "Temperature out of range"
          expect_text: "DHT22 values are in valid range"
      - name: Test humidity
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          path: /
          timeout: 10000
          fail_text: "Humidity out of range"
          expect_text: "DHT22 values are in valid range"
